# HTTP Server
server:
  port: ${PORT:2222}   # HTTP port
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ENDPOINT}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.atsistemas: 'DEBUG'

cygnus:
  sadr:
    name: sadr-service
    pingUrl: http://${cygnus.sadr.name}/sadr/ping/
    pingUrl: pepe1

spring:
   rabbitmq:
     host: rabbitmq
     port: 5672
     username: guest
     password: guest

